spring:
  application:
    name: Insurance-Claim-Management-System
  datasource:
    url: jdbc:mysql://localhost:3306/insurance_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  jwt:
    secret: hi@this@is@secret@key@for@jwt@token
    expirationMs: 86400000
  upload:
    base-dir: ./uploads


# file uploading config
#D:\Dev Work\INTELLIJ WORKSPACE\ICMSASSETS
#D:\Work\IntellijWorkspace\ICMSASSETS
icms-file-upload:
#      claims-dir: D:/Dev Work/INTELLIJ WORKSPACE/ICMSASSETS/
      claims-dir: D:/Work/IntellijWorkspace/ICMSASSETS
